defaults:
  - _self_
  - model_vec: glm # name of the vectorizer config
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: nsgaii


hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

return_value:
  # metric and dataset to optimize
  metric: ARI
  dataset: russe_bts-rnc-ru-train

model_clusterer:
  _target_: sklearn.cluster.AgglomerativeClustering
  n_clusters: [2, 3, 4, 5, 6, 7, 8, 9]
  affinity: [precomputed] # always use precomputed
  linkage: [average, complete, single]

eval_params:
  metrics: [
      seuclidean
  ]
  callable_metrics: [
      scipy.spatial.distance.cosine,
      scipy.spatial.distance.cityblock,
      scipy.spatial.distance.euclidean,
      scipy.spatial.distance.correlation,
      scipy.spatial.distance.hamming,
      __main__.norm_l1
  ]
  list_paths_datasets: [../../datasets/russe_bts-rnc]
