defaults:
  - _self_
  - model_vec: dm #dir and name of config your vectorizer
  - override hydra/sweeper: optuna #name of sweeper
  - override hydra/sweeper/sampler: nsgaii #name of sampler
  #cmaes, motpe, nsgaii, random, tpe

model_vec:
  _target_: DeepMistake_vectorizer.DMVectorizer
  path_to_scr: 'run_model.py'
  path_model: '../mean_dist_l1ndotn_CE'
  eval_flag: '--do_eval'
  eval_output_dir: 'predictions/'
  output_dir: '../mean_dist_l1ndotn_CE'
  loss: 'crossentropy_loss'
  pool_type: 'mean'
  symmetric: 'true'

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

return_value:
  #metric and dataset to optimization
  metric: ARI
  dataset: russe_bts-rnc-ru-train

model_clusterer:
  _target_: sklearn.cluster.SpectralClustering
  n_clusters: [2,3,4,5,6,7,8,9,10]
  affinity: [precomputed]
  assign_labels: [discretize]
  random_state: [0]

  #_target_: sklearn.cluster.AgglomerativeClustering
  #n_clusters: [2, 3, 4, 5, 6, 7]
  #affinity: [precomputed] #always use precomputed!!! all metrics you can insert into your code in def run():
  #linkage: [average, average, single]

  #_target_: sklearn.cluster.DBSCAN
  #eps: [0.1, 0.3, 0.45, 0.5, 0.55, 0.7]
  #min_samples: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  #metric: [precomputed]
  #algorithm: [auto]
