defaults:
  - _self_
  - model_vec: my_vec # my_vec glm bow

#hydra:
#  searchpath:
#    - file://C:/Users/79222/summer-wsi/GLM/conf/
#    - file://C:/Users/79222/summer-wsi/GLM
#    - file://C:/Users/79222/summer-wsi/

detector:
  path1:
  path2:
  wordlist:
  output_path: ../../../../results
  preload:
  save_embeds:
  dist_func: euclidean
  threshold: -0.15
  window: subword
  norm: False