defaults:
  - _self_
  - model_vec: glm  # my_vec glm bow

evaluator:
  input_path: ../../../../../datasets/se20lscd/de/sense_grouping.csv
  output_path: ../../../../results
  preload:  #../../../../vectors/dwug_de_glm.npy
  save_embeds: #../../../../vectors/dwug_de.npy
  eval_type: diachronic
  dist_func: euclidean
  threshold: 1.0
  window: subword
  visualize: True
  norm: False
  use_decision: True
  min_precision: 0.1